apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: quarkus-trade-orders
  name: quarkus-trade-orders
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: quarkus-trade-orders:latest
  postCommit: {}
  resources:
    limits:
      cpu: "4"
      memory: 7Gi
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/deewhyweb/quarkus-daytrader.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi-quarkus-native-s2i:20.1.0-java11
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: h0rDxkCpZXnsl--_Bgu0
    type: GitHub
  - generic:
      secret: wX2rK7pIjReKDL7gfnME
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
